from django.urls import path
from . import views

urlpatterns =[
    path('', views.Home, name='home'),
    path('about', views.About, name='about'),
    path('blog', views.Blog_view, name='blog'),
    path('Blog_Detail/<int:id>', views.Blog_Detail, name='Blog_Detail'),
    path('contact/', views.contact, name='contact'),
    path('team/', views.Team, name='team'),
    path('project/', views.project, name='project'),
    path('project_view/<int:id>', views.project_view, name='project_view'),
    path('appointment/', views.appointment, name='appointment'),
    path('subscribe/', views.subscribe, name='subscribe'),

    path('user_login', views.user_login, name='user_login'),
    path('UserLoginPage', views.UserLoginPage, name='UserLoginPage'),
    path('logout', views.Logout, name='logout'),

    path('AdminDashboard', views.AdminDashboard, name='AdminDashboard'),
    path('admin_profile', views.admin_profile, name='admin_profile'),
    path('admin_update', views.admin_update, name='admin_update'),
    path('admin_notification/', views.admin_notification, name='admin_notification'),
    path('delete_notifications/<int:id>', views.delete_notifications, name='delete_notifications'),
    path('add_staff/', views.add_staff, name='add_staff'),
    path('staff_list/', views.staff_list, name='staff_list'),
    path('search_staff/', views.search_staff, name='search_staff'),
    path('edit_staff/<int:staff_id>', views.edit_staff, name='edit_staff'),
    path('delete_staff/<int:staff_id>', views.delete_staff, name='delete_staff'),
    path('create_admin_blog/', views.create_admin_blog, name='create_admin_blog'),
    path('admin_blogs/', views.admin_blogs, name='admin_blogs'),
    path('search_ablog/', views.search_ablog, name='search_ablog'),
    path('edit_admin_blog/<int:id>', views.edit_admin_blog, name='edit_admin_blog'),
    path('delete_item/<int:id>', views.delete_item, name='delete_item'),
    path('admin_project_list', views.admin_project_list, name='admin_project_list'),
    path('search_aproject/', views.search_aproject, name='search_aproject'),
    path('admin_project_view/<int:id>/', views.admin_project_view, name='admin_project_view'),
    path('delete_project/<int:id>', views.delete_project, name='delete_project'),
    path('appointment_list', views.appointment_list, name='appointment_list'),
    path('appointment_view/<int:id>', views.appointment_view, name='appointment_view'),
    path('schedule/<int:id>/', views.schedule, name='schedule'),
    path('schedule_appointment/<int:id>', views.schedule_appointment, name='schedule_appointment'),
    path('schedule_app_view/<int:id>', views.schedule_app_view, name='schedule_app_view'),
    path('reject_appointment/<int:id>', views.reject_appointment, name='reject_appointment'),
    path('services_list/', views.services_list, name='services_list'),
    path('create_services/', views.create_services, name='create_services'),
    path('edit_services/<int:id>/', views.edit_services, name='edit_services'),
    path('delete_services/<int:id>/', views.delete_services, name='delete_services'),
    path('search_view/', views.search_view, name='search_view'),



    path('staff_dashboard/', views.staff_dashboard, name='staff_dashboard'),
    path('staff_appointments/', views.staff_appointments, name='staff_appointments'),
    path('search_app/', views.search_app, name='search_app'),
    path('staff_app_view/<int:id>/<int:id1>/', views.staff_app_view, name='staff_app_view'),
    path('staff_reject_appointment/<int:id>', views.staff_reject_appointment, name='staff_reject_appointment'),
    path('staff_blog/', views.staff_blog, name='staff_blog'),
    path('search_sblog/', views.search_sblog, name='search_sblog'),
    path('create_staff_blog/', views.create_staff_blog, name='create_staff_blog'),
    path('edit_staff_blog/<int:id>', views.edit_staff_blog, name='edit_staff_blog'),
    path('staff_project_list', views.staff_project_list, name='staff_project_list'),
    path('search_sproject/', views.search_sproject, name='search_sproject'),
    path('project_schedule/<int:id>/<int:id1>/', views.project_schedule, name='project_schedule'),
    path('project_form', views.project_form, name='project_form'),
    path('staff_project_view/<int:id>/<int:id1>/', views.staff_project_view, name='staff_project_view'),
    path('staff_project_update/<int:id>/', views.staff_project_update, name='staff_project_update'),
    path('project_form_update/<int:id>/', views.project_form_update, name='project_form_update'),
    path('staff_notification', views.staff_notification, name='staff_notification'),
    path('delete_notification/<int:id>', views.delete_notification, name='delete_notification'),
    path('staff_myproject_list/', views.staff_myproject_list, name='staff_myproject_list'),
    path('search_myproject/', views.search_myproject, name='search_myproject'),
    path('staff_myproject_view/<int:id>/', views.staff_myproject_view, name='staff_myproject_view'),
    path('staff_profile', views.staff_profile, name='staff_profile'),
    path('request_update', views.request_update, name='request_update'),

    path('client_profile/', views.client_profile, name='client_profile'),
    path('design_preference/', views.design_preference, name='design_preference'),
    path('delete_design_preference/<int:id>/', views.delete_design_preference, name='delete_design_preference'),
    path('project_updates/', views.project_updates, name='project_updates'),
    path('client_notification/', views.client_notification, name='client_notification'),
    path('delete_client_notification/<int:id>', views.delete_client_notification, name='delete_client_notification'),
    path('client_review', views.client_review, name='client_review'),

]