# Generated by Django 5.0.6 on 2024-06-26 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('future_app', '0004_remove_user_name_staff_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
