# Generated by Django 5.0.6 on 2024-06-26 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('future_app', '0005_alter_staff_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
