# Generated by Django 5.0.6 on 2024-06-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('future_app', '0010_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
