# Generated by Django 5.0.6 on 2024-07-06 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('future_app', '0013_appointment_status_blog_exp_blog_image1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='staff_name',
            field=models.ForeignKey(default=16, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
