# Generated by Django 5.0.6 on 2024-07-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('future_app', '0014_appointment_staff_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.IntegerField(choices=[(1, 'pending'), (2, 'Scheduled'), (3, 'Rejected')], default=1),
        ),
    ]
