# Generated by Django 5.0.6 on 2024-07-10 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('future_app', '0015_alter_appointment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='email',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='name',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='phone',
        ),
    ]
