# Generated by Django 5.0.6 on 2024-07-10 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('future_app', '0017_appointment_client_alter_appointment_staff_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='staff_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments_as_staff', to=settings.AUTH_USER_MODEL),
        ),
    ]
