# Generated by Django 5.0.6 on 2024-07-10 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('future_app', '0018_alter_appointment_staff_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='address',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
