# Generated by Django 5.0.6 on 2024-07-11 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('future_app', '0020_blog_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='user_id',
            new_name='user',
        ),
    ]
