# Generated by Django 5.0.6 on 2024-07-11 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('future_app', '0021_rename_user_id_blog_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='author',
        ),
    ]
