# Generated by Django 5.0.6 on 2024-07-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('future_app', '0024_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
