# Generated by Django 5.0.6 on 2024-07-20 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('future_app', '0025_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(blank=True, max_length=50, null=True)),
                ('color_palette', models.CharField(blank=True, max_length=50, null=True)),
                ('materials', models.CharField(blank=True, max_length=50, null=True)),
                ('budget', models.CharField(blank=True, max_length=50, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
