# Generated by Django 5.0.6 on 2024-07-21 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('future_app', '0026_designpreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Scheduled'), (3, 'Accepted'), (4, 'Rejected')], default=1),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(1, 'In Progress'), (2, 'On Hold'), (3, 'Completed')], default='1', max_length=20)),
                ('starting_date', models.DateField(blank=True, null=True)),
                ('ending_date', models.DateField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='project_as_client', to=settings.AUTH_USER_MODEL)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_as_client', to='future_app.designpreference')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_as_staff', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
