# Generated by Django 5.0.6 on 2024-07-24 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('future_app', '0028_project_actual_budget_project_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
