# Generated by Django 5.0.6 on 2024-07-24 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('future_app', '0029_project_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
