# Generated by Django 5.0.6 on 2024-08-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('future_app', '0034_rename_main_image_project_mainimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='designpreference',
            name='layout',
            field=models.CharField(blank=True, default='3 BHK', max_length=50, null=True),
        ),
    ]
