# Generated by Django 5.0.6 on 2024-08-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('future_app', '0035_designpreference_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, default='Interior', max_length=50, null=True),
        ),
    ]
