# Generated by Django 5.0.6 on 2024-08-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('future_app', '0036_project_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
